#!/usr/bin/env bash
#
# vllm-mlx-siesta one-liner installer for macOS.
#
# Installs siesta via pipx (or uv if present), writes a default config,
# renders the LaunchAgent plist, and loads it so the proxy starts at login.
#
# Usage (curl | bash):
#   curl -fsSL https://raw.githubusercontent.com/axiomantic/vllm-mlx-siesta/main/install.sh | bash
#   curl -fsSL https://raw.githubusercontent.com/axiomantic/vllm-mlx-siesta/main/install.sh | bash -s -- \
#       --model mlx-community/Qwen2.5-7B-Instruct-4bit \
#       --listen-port 8080 --upstream-port 8000
#
# Flags:
#   --model MODEL         HuggingFace model id (default: mlx-community/Qwen2.5-7B-Instruct-4bit)
#   --listen-port N       siesta's listen port (default: 8080)
#   --upstream-port N     vllm-mlx port (default: 8000)
#   --pause N             SIGSTOP after N seconds idle (default: 60)
#   --idle N              SIGTERM after N seconds idle (default: 600)
#   --ref REF             git ref to install from (default: main)
#   --no-launchd          skip LaunchAgent install (config + binary only)
#   --uninstall           reverse the install

set -euo pipefail

REPO="https://github.com/axiomantic/vllm-mlx-siesta.git"
RAW="https://raw.githubusercontent.com/axiomantic/vllm-mlx-siesta"
LABEL="com.axiomantic.vllm-mlx-siesta"

MODEL="mlx-community/Qwen2.5-7B-Instruct-4bit"
LISTEN_PORT=8080
UPSTREAM_PORT=8000
PAUSE=60
IDLE=600
REF="main"
SKIP_LAUNCHD=0
UNINSTALL=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --model) MODEL="$2"; shift 2 ;;
    --listen-port) LISTEN_PORT="$2"; shift 2 ;;
    --upstream-port) UPSTREAM_PORT="$2"; shift 2 ;;
    --pause) PAUSE="$2"; shift 2 ;;
    --idle) IDLE="$2"; shift 2 ;;
    --ref) REF="$2"; shift 2 ;;
    --no-launchd) SKIP_LAUNCHD=1; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    -h|--help) sed -n '3,25p' "$0"; exit 0 ;;
    *) echo "unknown flag: $1" >&2; exit 2 ;;
  esac
done

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "error: this installer is macOS only" >&2
  exit 1
fi

LAUNCH_AGENTS="$HOME/Library/LaunchAgents"
PLIST_DEST="$LAUNCH_AGENTS/$LABEL.plist"
CONFIG_DIR="$HOME/.config/vllm-mlx-siesta"
CONFIG_PATH="$CONFIG_DIR/config.toml"
LOG_DIR="$HOME/Library/Logs/vllm-mlx-siesta"

if [[ $UNINSTALL -eq 1 ]]; then
  if [[ -f "$PLIST_DEST" ]]; then
    launchctl unload "$PLIST_DEST" 2>/dev/null || true
    rm -f "$PLIST_DEST"
    echo "removed $PLIST_DEST"
  fi
  if command -v pipx >/dev/null 2>&1; then
    pipx uninstall vllm-mlx-siesta 2>/dev/null || true
  fi
  if command -v uv >/dev/null 2>&1; then
    uv tool uninstall vllm-mlx-siesta 2>/dev/null || true
  fi
  echo "config kept at $CONFIG_PATH; remove manually if desired"
  exit 0
fi

# --- 1. Install the siesta binary ------------------------------------------------

if command -v uv >/dev/null 2>&1; then
  echo ">> installing vllm-mlx-siesta via uv tool"
  uv tool install --force --python 3.11 "git+$REPO@$REF"
  SIESTA_BIN="$(uv tool dir)/vllm-mlx-siesta/bin/vllm-mlx-siesta"
  [[ -x "$SIESTA_BIN" ]] || SIESTA_BIN="$HOME/.local/bin/vllm-mlx-siesta"
elif command -v pipx >/dev/null 2>&1; then
  echo ">> installing vllm-mlx-siesta via pipx"
  pipx install --force "git+$REPO@$REF"
  SIESTA_BIN="$(pipx environment --value PIPX_BIN_DIR 2>/dev/null || echo "$HOME/.local/bin")/vllm-mlx-siesta"
else
  if command -v brew >/dev/null 2>&1; then
    echo ">> pipx not found; installing via homebrew"
    brew install pipx
    pipx ensurepath
    pipx install --force "git+$REPO@$REF"
    SIESTA_BIN="$(pipx environment --value PIPX_BIN_DIR 2>/dev/null || echo "$HOME/.local/bin")/vllm-mlx-siesta"
  else
    echo "error: need uv, pipx, or homebrew to install siesta" >&2
    echo "  https://github.com/astral-sh/uv  OR  https://pipx.pypa.io" >&2
    exit 1
  fi
fi

if [[ ! -x "$SIESTA_BIN" ]]; then
  echo "warning: could not confirm siesta binary at $SIESTA_BIN"
  echo "         check your PATH; LaunchAgent may fail until the binary is found"
fi

if ! command -v vllm-mlx >/dev/null 2>&1; then
  echo "!! vllm-mlx not found on PATH."
  echo "   Install it before the LaunchAgent will successfully serve requests:"
  echo "     https://github.com/waybarrios/vllm-mlx"
fi

# --- 2. Write config --------------------------------------------------------------

mkdir -p "$CONFIG_DIR"
if [[ -f "$CONFIG_PATH" ]]; then
  echo ">> keeping existing $CONFIG_PATH"
else
  cat > "$CONFIG_PATH" <<EOF
# Generated by vllm-mlx-siesta install.sh
listen_host = "127.0.0.1"
listen_port = $LISTEN_PORT

upstream_host = "127.0.0.1"
upstream_port = $UPSTREAM_PORT
model = "$MODEL"

pause_after_seconds = $PAUSE.0
idle_timeout_seconds = $IDLE.0
EOF
  echo ">> wrote $CONFIG_PATH"
fi

mkdir -p "$LOG_DIR"

# --- 3. LaunchAgent ---------------------------------------------------------------

if [[ $SKIP_LAUNCHD -eq 1 ]]; then
  echo ">> skipping LaunchAgent (--no-launchd)"
else
  mkdir -p "$LAUNCH_AGENTS"
  TMPL_URL="$RAW/$REF/launchd/com.axiomantic.vllm-mlx-siesta.plist.tmpl"
  TMPL="$(mktemp)"
  trap 'rm -f "$TMPL"' EXIT
  curl -fsSL -o "$TMPL" "$TMPL_URL"

  escape() { printf '%s' "$1" | sed -e 's/[\/&|]/\\&/g'; }
  AGENT_PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
  sed \
    -e "s|__SIESTA_BIN__|$(escape "$SIESTA_BIN")|g" \
    -e "s|__CONFIG_PATH__|$(escape "$CONFIG_PATH")|g" \
    -e "s|__LOG_DIR__|$(escape "$LOG_DIR")|g" \
    -e "s|__WORKDIR__|$(escape "$HOME")|g" \
    -e "s|__PATH__|$(escape "$AGENT_PATH")|g" \
    "$TMPL" > "$PLIST_DEST"

  launchctl unload "$PLIST_DEST" 2>/dev/null || true
  launchctl load "$PLIST_DEST"
  echo ">> loaded $PLIST_DEST"
fi

cat <<EOF

siesta is installed.

  binary:   $SIESTA_BIN
  config:   $CONFIG_PATH (edit to change model / timeouts)
  logs:     $LOG_DIR
  launchd:  ${PLIST_DEST}$([[ $SKIP_LAUNCHD -eq 1 ]] && echo "  (skipped)")

Test once vllm-mlx is installed:
  curl http://127.0.0.1:$LISTEN_PORT/healthz

Uninstall:
  curl -fsSL $RAW/$REF/install.sh | bash -s -- --uninstall
EOF
